# yaml-language-server: $schema=https://raw.githubusercontent.com/kiliantyler/Kometa/update-jsonschema/json-schema/config-schema.json
libraries:
  Movies:
    collection_files:
    - default: basic
    - default: imdb
    - folder: /config/collections/common
    - folder: /config/collections/movies
    settings:
      asset_directory: /assets/Movies
      prioritize_assets: true
    operations:
      assets_for_all: true

settings:
  cache: true
  cache_expiration: 60
  asset_directory: /assets
  asset_folders: true
  asset_depth: 1
  create_asset_folders: true
  prioritize_assets: true
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: false
  sync_mode: sync
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: false
  show_filtered: false
  show_options: false
  show_missing: false
  show_missing_assets: false
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_users: all
  playlist_exclude_users:
  playlist_report: false
  verify_ssl: true
  custom_repo: ""
  show_unconfigured: true

plex:
  url: http://plex.media.svc.cluster.local:32400
  token: <<PLEX_API_KEY>>
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false

radarr:
  url: http://radarr.arrs.svc.cluster.local
  token: <<RADARR_API_KEY>>
  add_missing: true
  add_existing: false
  root_folder_path: /media/Movies
  monitor: true
  availability: announced
  quality_profile: "HD Bluray + WEB"
  tag: kometa
  search: true
  radarr_path:
  plex_path:
  upgrade_existing: false

sonarr:
  url: http://sonarr.arrs.svc.cluster.local
  token: <<SONARR_API_KEY>>
  add_missing: true
  add_existing: false
  root_folder_path: /media/TV
  monitor: all
  quality_profile: Web 1080p
  language_profile: English
  series_type: standard
  season_folder: true
  tag: kometa
  search: true
  cutoff_search: false
  sonarr_path:
  plex_path:
  upgrade_existing: false

tautulli:
  url: http://tautulli.observability.svc.cluster.local
  apikey: <<TAUTULLI_API_KEY>>

tmdb:
  apikey: <<TMDB_API_KEY>>
  language: en
  cache_expiration: 60
  region: US

github:
  token: <<GITHUB_TOKEN>>

omdb:
  apikey: <<OMDB_API_KEY>>
  cache_expiration: 60

mdblist:
  apikey: <<MDBLIST_API_KEY>>
  cache_expiration: 60

trakt:
  client_id: <<TRAKT_CLIENT_ID>>
  client_secret: <<TRAKT_CLIENT_SECRET>>
  authorization:
    access_token: <<TRAKT_ACCESS_TOKEN>>
    token_type: Bearer
    expires_in: 7889238
    refresh_token: <<TRAKT_REFRESH_TOKEN>>
    scope: public
    created_at: 1728515405
  pin:

anidb:
  client: <<ANIDB_CLIENT>>
  version: 1
  language: en
  cache_expiration: 60
